- hosts: localhost
  name: main
  vars:
    source_key: "./keys/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    source_pub_key: "./keys/id_ed25519.pub"
    dest_pub_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
    brew_casks:
      - google-chrome
      - gimp
      - discord
      - bitwarden
      - docker
      - firefox
      - rectangle
      - hiddenbar
      - numi
      - maccy
    brew_packages:
      - nasm
      - cocoapods
      - curl
      - awscli
      - jq
      - neofetch
      - tree
      - redis
      - ruby
      - git
      - fzf
      - gcc
      - coreutils
      - gnu-getopt
      - gnu-indent
      - gnu-sed
      - gnu-tar
      - gnu-typist
      - gnupg
      - gnutls
      - gawk
      - ffmpeg
      - pyenv
      - gh
      - go
      - rustup-init
      - n
      - bat
      - cmake
      - elixir
      - neovim
      - terraform
      - tmux
      - grep
      - imagemagick
      - ripgrep
      - protobuf
      - wget
      - lua
      - cmake
      - tree-sitter
    brew_tap:
      - FelixKratz/formulae
  tasks:
  - include_tasks: tasks/brewtap.yaml
  - include_tasks: tasks/installhomebrew.yaml
  - include_tasks : tasks/installprograms.yaml
  - include_tasks: tasks/installcasks.yaml
  - include_tasks: tasks/ssh.yaml
  - include_tasks: tasks/dotfiles.yaml
  - include_tasks: tasks/zsh.yaml
  - include_tasks: tasks/node.yaml
  - include_tasks: tasks/rust.yaml
