- name: clone dotfiles repo
  ansible.builtin.git:
    repo: 'git@github.com:vibovenkat123/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    version: main
    update: yes
    accept_hostkey: yes
  tags:
    - dotfiles
    - neovim
    - zsh
    - tmux
- name: link files
  ansible.builtin.shell: cd $HOME/.dotfiles && ./dotfiles_setup
  tags:
    - neovim
    - zsh
    - tmux
    - dotfiles
- name: remove the directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles"
    state: absent
- name: readd it but make it bare
- name: clone dotfiles repo
  ansible.builtin.git:
    repo: 'git@github.com:vibovenkat123/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    version: main
    update: yes
    bare: true
    accept_hostkey: yes
