- name: readd it but make it bare
  ansible.builtin.git:
    repo: 'git@github.com:vibovenkat123/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    version: main
    update: yes
    bare: true
    accept_hostkey: yes
  tags:
    - dotfiles
    - neovim
    - zsh
    - tmux

- name: checkout
  ansible.builtin.shell:
    cmd: git --git-dir="$HOME/.dotfiles" --work-tree="$HOME" checkout
    executable: /bin/zsh
